services:
  - type: web
    name: perimeter-safe
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
